service:
  name: sls-restapi-starter

plugins:
  - serverless-plugin-typescript
  - serverless-deployment-bucket
  - serverless-layers
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2
  stage: ${opt:stage, 'dev'}
  environment:
    PROD_MODE: ${self:provider.stage}

  deploymentBucket:
    name: ${self:service}-bucket-${self:provider.stage}

functions:
  App:
    handler: src/app.appHandler
    memorySize: 192
    timeout: 10
    events:
      - http:
          method: any
          path: /app/{proxy+}
          cors: true
